# Required Group Variables
  # REGISTRY_SERVER:
  # REGISTRY_SERVER_CONNECTION:

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - azure-pipelines.yml
    - /pipelines/*
    - /src/*
    exclude:
    - /**/*.md

variables:
- group: 'deploy-group'
- name: 'ImageName'
  value: 'danielscholl/spring-function-app'

stages:
- template: pipelines/stages.yml
  parameters:
    environments:
    - name: 'dockerhub'
      acrRegistryName: $(REGISTRY_SERVER)
      acrServiceConnection: $(REGISTRY_SERVICE_CONNECTION)
