# Required Group Variables
# SERVICE_ENDPOINT:
# FUNCTION_APP_NAME:

trigger:
- master

variables:
- group: deploy-group

pool:
  vmImage: 'ubuntu-latest'

# Maven Package - create the function artifacts in
steps:
- task: Maven@2
  displayName: 'Maven pom.xml'
  inputs:
    mavenPomFile: './pom.xml'

# Copy files
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/azure-functions/**'
    TargetFolder: '$(build.artifactstagingdirectory)'

# Deploy using Azure App Service Deploy - Webdeployment
- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy: javapipeline'
  inputs:
    azureSubscription: '$(SERVICE_ENDPOINT)'
    appType: functionApp
    WebAppName: $(FUNCTION_APP_NAME)
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    enableCustomDeployment: true
    DeploymentType: runFromZip
    TakeAppOfflineFlag: false
    ExcludeFilesFromAppDataFlag: false
    RenameFilesFlag: false
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
