# Required Group Variables
# SERVICE_ENDPOINT:
# APP_NAME:
# REGISTRY_SERVER:
# REGISTRY_SERVICE_CONNECTION:

trigger:
- master

variables:
- group: deploy-group

parameters:
  isDocker: true

pool:
  vmImage: 'ubuntu-latest'

jobs:

# This Job will build and push a Docker Container to the Registry
- job: Docker
  displayName: Build and Push Docker Image
  condition: eq('${{ parameters.isDocker }}', true)
  steps:
  - task: Docker@2
    displayName: Docker Build and Push
    inputs:
      command: buildAndPush
      repository: $(REGISTRY_SERVER)
      dockerfile: Dockerfile
      containerRegistry: $(REGISTRY_SERVICE_CONNECTION)
      tags: |
        $(Build.BuildId)
        latest

# This Job will compile code and load to artifact.
- job: build
  displayName: Compile
  condition: eq('${{ parameters.isDocker }}', false)
  steps:
  - task: Maven@3
    displayName: 'Maven pom.xml'
    inputs:
      mavenPomFile: './pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean install'
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: '**/target/**'
      TargetFolder: '$(build.artifactstagingdirectory)'
    condition: succeededOrFailed()
  - upload: $(Build.ArtifactStagingDirectory)
    artifact: drop

# This job will deploy code to a Function App
- job: deploy
  displayName: Deploy
  dependsOn: build
  condition: eq('${{ parameters.isDocker }}', false)
  steps:
  - download: current
  - task: AzureFunctionApp@1
    displayName: 'Deploy Azure Function App'
    inputs:
      azureSubscription: $(SERVICE_ENDPOINT)
      appType: 'Linux'
      appName: $(APP_NAME)
      package: $(Pipeline.Workspace)/drop/target/azure-functions/$(APP_NAME)/Hello-World
