trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - azure-pipelines.yml
    - /pipelines/*
    - /src/*
    exclude:
    - /**/*.md

variables:
- group: 'acr-variables'
  ImageName: 'spring-function-app'

stages:
- template: pipelines/stages.yml
  parameters:
    environments:
    - name: 'dev'
      acrRegistryName: $(ACR_DEV_NAME)
      acrServiceConnection: $(ACR_DEV_CONNECTION)
    - name: 'qa'
      acrRegistryName: $(ACR_QA_NAME)
      acrServiceConnection: $(ACR_QA_CONNECTION)
    - name: 'prod'
      acrRegistryName: $(ACR_QA_NAME)
      acrServiceConnection: $(ACR_PROD_CONNECTION)
