# Required Group Variables
  # REGISTRY_SERVER:
  # REGISTRY_SERVER_CONNECTION:

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - azure-pipelines.yml
    - /pipelines/*
    - /src/*
    exclude:
    - /**/*.md

variables:
- group: 'deploy-group'
- name: 'ImageName'
  value: 'spring-function-app'
- isDockerhub: ${{ not(contains(variables['REGISTRY_SERVER'], 'azurecr.io')) }}
  ${{ if eq(variables.isDockerhub, 'true') }}:
    FullImage: $REGISTRY_SERVER/$ImageName
  ${{ if eq(variables.isDockerhub, 'false') }}:
    FullImage: $ImageName

stages:
- template: pipelines/stages.yml
  parameters:
    environments:
    - name: 'dockerhub'
      acrRegistryName: $(REGISTRY_SERVER)
      acrServiceConnection: $(REGISTRY_SERVICE_CONNECTION)
