# Required Group Variables
  # REGISTRY_SERVER:
  # REGISTRY_SERVER_CONNECTION:

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - azure-pipelines.yml
    - /pipelines/*
    - /src/*
    exclude:
    - /**/*.md

variables:
- group: 'deploy-group'
- name: 'ImageName'
  value: 'spring-function-app'
# - name: 'isACR'
#   value: ${{ contains(variables['REGISTRY_SERVER'], 'azurecr.io') }}
# - name: 'FullImageName'
#   value: if(eq(variables.isACR, 'true'), $(ImageName), $(REGISTRY_SERVER)/$(ImageName)))
- name: 'FullImageName'
  value: $(REGISTRY_SERVER)/$(ImageName)

stages:
- template: pipelines/stages.yml
  parameters:
    environments:
    - name: 'dockerhub'
      acrRegistryName: $(REGISTRY_SERVER)
      acrServiceConnection: $(REGISTRY_SERVICE_CONNECTION)
      acrImageName: $(FullImageName)
