version: '3.7'

services:
  spring-function-app:
    env_file:
      - .env
    image: ${REGISTRY}/spring-function-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    restart: always
