- job: build
  displayName: Compile
  steps:
  - task: Maven@3
    displayName: 'Maven pom.xml'
    inputs:
      mavenPomFile: './pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean install'
  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: '**/target/**'
      TargetFolder: '$(build.artifactstagingdirectory)'
    condition: succeededOrFailed()
  - upload: $(Build.ArtifactStagingDirectory)
    artifact: drop
