jobs:
  - job: Build
    displayName: 'Docker'
    steps:
    - task: Docker@2
      displayName: 'Docker Build'
      inputs:
        repository: '$(ImageName)'
        command: build
        Dockerfile: Dockerfile
        tags: $(Build.BuildId)

    - task: Docker@2
      displayName: 'Docker Save'
      inputs:
        repository: '$(ImageName)'
        command: save
        arguments: '--output $(build.artifactstagingdirectory)/$(ImageName).image.tar $(ImageName):$(Build.BuildId)'
        addPipelineData: false

    - task: PublishPipelineArtifact@1
      displayName: 'Docker Push (Artifact)'
      inputs:
        path: $(build.artifactstagingdirectory)
        artifact: ContainerImage
