jobs:
  - deployment: ${{ parameters.environment }}
    displayName: 'Deploy'
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Docker@2
            displayName: 'Docker Load'
            inputs:
              command: load
              arguments: '--input $(Pipeline.Workspace)/ContainerImage/$(ImageName).image.tar'

          - task: Docker@2
            displayName: 'Docker Tag $(Build.BuildId)'
            inputs:
              containerRegistry: ${{ parameters.acr_service_connection }}
              repository: '$(ImageName)'
              command: tag
              arguments: '$(ImageName):$(Build.BuildId) ${{ parameters.acr_registry_name }}/$(ImageName):$(Build.BuildId)'

          - task: Docker@2
            displayName: 'Docker Tag latest'
            inputs:
              containerRegistry: ${{ parameters.acr_service_connection }}
              repository: '$(ImageName)'
              command: tag
              arguments: '$(ImageName):$(Build.BuildId) ${{ parameters.acr_registry_name }}/$(ImageName):latest'

          - task: Docker@2
            displayName: 'Docker Push'
            inputs:
              containerRegistry: ${{ parameters.acr_service_connection }}
              repository: '$(ImageName)'
              command: push
              tags: |
                $(Build.BuildId)
                latest
