parameters:
  environments: []

stages:

- stage: mvntest
  displayName: 'mvn test'
  jobs:
  - template: build.yml

- stage: dockerbuild
  displayName: 'docker build'
  jobs:
  - template: docker-build.yml

- ${{ each environment in parameters.environments }}:
  - stage: ${{ environment.name }}_deploy
    displayName: 'docker push image-${{ environment.name }}'
    jobs:
    - template: docker-push.yml
      parameters:
        environment: ${{ environment.name }}
        acr_registry_name: ${{ environment.acrRegistryName }}
        acr_service_connection: ${{ environment.acrServiceConnection }}
