parameters:
  environments: []

stages:

- stage: mvntest
  displayName: 'Prepare'
  jobs:
  - template: test.yml
  - template: docker-build.yml

- ${{ each environment in parameters.environments }}:
  - stage: ${{ environment.name }}_deploy
    displayName: 'Deploy ${{ environment.name }}'
    jobs:
    - template: docker-push.yml
      parameters:
        environment: ${{ environment.name }}
        acr_registry_name: ${{ environment.acrRegistryName }}
        acr_service_connection: ${{ environment.acrServiceConnection }}
