parameters:
  environments: []

stages:

- stage: ci
  displayName: 'Build Project'
  jobs:
  - template: build.yml

- ${{ each environment in parameters.environments }}:
  - stage: ${{ environment.name }}_deploy
    displayName: 'Deploy Project-${{ environment.name }}'
    jobs:
    - template: deploy.yml
      parameters:
        environment: ${{ environment.name }}
        acr_registry_name: ${{ environment.acrRegistryName }}
        acr_service_connection: ${{ environment.acrServiceConnection }}
